export const portfolioData = [
  {
    id: 240,
    title: "ফ্রেশ_কেয়ার",
    category: "Landing Page",
    img: "https://res.cloudinary.com/dc81z6ykt/image/upload/v1692995752/jadutech/landing-page-1_geoigm.jpg",
    subtitle: `হোম মেইড সাবানের ল্যান্ডিং পেইজ`,
    key: "হোম মেইড সাবানের ল্যান্ডিং পেইজ সাবান home made landing page cartflows soap",
    url: "https://freshcarebd.com/",
    compatible: [
      "<span class='lang-dot wp'></span>WordPress",
      "<span class='lang-dot el'></span>Elementor",
      "<span class='lang-dot wc'></span>WooCommerce",
      "<span class='lang-dot bs'></span>Cartflows",
    ],
  },
  {
    id: 230,
    title: "Grm_Family_Law",
    category: "Lawyers",
    img: "https://res.cloudinary.com/getmonirh/image/upload/v1643886847/monirhossain/portfolio/grmfamilylaw-cm_seemyl.png",
    subtitle: `Portland Divorce Lawyers`,
    key: "Grm Family Law Portland Divorce Lawyers Yoast SEO WordPress elementor",
    url: "https://grmfamilylaw.com/",
    compatible: [
      "<span class='lang-dot wp'></span>WordPress",
      "<span class='lang-dot el'></span>Elementor",
      "<span class='lang-dot php'></span>Yoast SEO",
    ],
  },
  {
    id: 1,
    title: "Natkam",
    category: "Kids",
    img: "https://res.cloudinary.com/getmonirh/image/upload/v1643888114/monirhossain/portfolio/natkam_tesdav.png",
    subtitle: `Natkam summer camp website`,
    key: "Natkam Natkam summer camp website Yoast SEO WordPress elementor",
    url: "https://natkam.cat/",
    compatible: [
      "<span class='lang-dot wp'></span>WordPress",
      "<span class='lang-dot el'></span>Elementor",
      "<span class='lang-dot php'></span>Yoast SEO",
      "<span class='lang-dot bt'></span>MailChimp",
    ],
  },
  {
    id: 2,
    title: "Joe_Coffee",
    category: "Online Shop",
    img: "https://res.cloudinary.com/getmonirh/image/upload/v1643609197/monirhossain/portfolio/joecoffeecompany_py8mzv.jpg",
    subtitle: "Coffee company eCommerce website",
    key: "coffee online shop ecommerce wordpress elementor woocommerce joe coffee company",
    url: "https://joecoffeecompany.com/",
    compatible: [
      "<span class='lang-dot wp'></span>WordPress",
      "<span class='lang-dot el'></span>Elementor",
      "<span class='lang-dot wc'></span>WooCommerce",
    ],
  },
  {
    id: 2,
    title: "C&W_Plumbing",
    category: "Plumbing",
    img: "https://res.cloudinary.com/getmonirh/image/upload/v1646499335/monirhossain/portfolio/candwplumbing_kciuan.png",
    subtitle: "Plumbers Company Website Design",
    key: "Plumbers Plumbing wordpress elementor woocommerce booking",
    url: "https://candwplumbing.com/",
    compatible: [
      "<span class='lang-dot wp'></span>WordPress",
      "<span class='lang-dot el'></span>Elementor",
    ],
  },
  {
    id: 3,
    title: "Flwr",
    category: "Flower Shop",
    img: "https://res.cloudinary.com/getmonirh/image/upload/v1643609196/monirhossain/portfolio/flwr_bost6f.jpg",
    subtitle: "Flower shop with WooCommerce",
    key: "flower online shop ecommerce wordpress elementor woocommerce flwr",
    url: "https://www.flwr.co.nz/",
    compatible: [
      "<span class='lang-dot wp'></span>WordPress",
      "<span class='lang-dot el'></span>Elementor",
      "<span class='lang-dot wc'></span>WooCommerce",
    ],
  },
  {
    id: 4,
    title: "Twelve_Beauty",
    category: "Beauty Shop",
    img: "https://res.cloudinary.com/getmonirh/image/upload/v1643609196/monirhossain/portfolio/twelvebeauty_qzoxyp.jpg",
    key: "beauty online shop ecommerce wordpress elementor woocommerce cosmetics shop twelve beauty",
    subtitle: "Online cosmetics shop",
    url: "https://www.twelvebeauty.com/",
    compatible: [
      "<span class='lang-dot wp'></span>WordPress",
      "<span class='lang-dot el'></span>Elementor",
      "<span class='lang-dot wc'></span>WooCommerce",
    ],
  },
  {
    id: 5,
    title: "Sporsha",
    category: "Charity / Non-profit",
    img: "https://res.cloudinary.com/getmonirh/image/upload/v1643609197/monirhossain/portfolio/sporsha_wf2gp0.jpg",
    subtitle: "",
    key: "sporsha charity no-profit elementor astra woocommerce wordpress",
    url: "https://sporsha.org/",
    compatible: [
      "<span class='lang-dot wp'></span>WordPress",
      "<span class='lang-dot el'></span>Elementor",
    ],
  },
  {
    id: 6,
    title: "Fix_and_Go",
    category: "Online Shop",
    img: "https://res.cloudinary.com/getmonirh/image/upload/v1643609197/monirhossain/portfolio/fixandgony_nv4moc.jpg",
    subtitle: "",
    key: "mobile repair fix wordpress elementor go fix and go ny woocommerce ecommerce",
    url: "https://fixandgony.com/",
    compatible: [
      "<span class='lang-dot wp'></span>WordPress",
      "<span class='lang-dot el'></span>Elementor",
      "<span class='lang-dot wc'></span>WooCommerce",
    ],
  },
  {
    id: 7,
    title: "Fixiz",
    category: "Cleaning",
    img: "https://res.cloudinary.com/getmonirh/image/upload/v1643609197/monirhossain/portfolio/fixiz_fly5st.jpg",
    subtitle: "",
    key: "cleaning services fix home services wordpress elementor serviceos fixiz cleaning",
    url: "https://fixiz.co.uk/",
    compatible: [
      "<span class='lang-dot wp'></span>WordPress",
      "<span class='lang-dot el'></span>Elementor",
    ],
  },
  {
    id: 8,
    title: "Nordic_Appeal",
    category: "WooCommerce",
    img: "https://res.cloudinary.com/getmonirh/image/upload/v1643609197/monirhossain/portfolio/nordicappeal_uyac3o.jpg",
    subtitle: "Apple accessories online shop",
    key: "nordic appeal apple imac mackbook wordpress woocommerce elementor ",
    url: "https://www.nordicappeal.com/",
    compatible: [
      "<span class='lang-dot wp'></span>WordPress",
      "<span class='lang-dot el'></span>Elementor",
      "<span class='lang-dot wc'></span>WooCommerce",
    ],
  },
  {
    id: 9,
    title: "Fhitting_Room",
    category: "Health / Fitness",
    img: "https://res.cloudinary.com/getmonirh/image/upload/v1643609197/monirhossain/portfolio/fhittingroom_ub7n9b.jpg",
    subtitle: "Gym website with wordpress",
    key: "gym fit health fintness fhitting room wordpress elementor",
    url: "https://www.fhittingroom.com/",
    compatible: [
      "<span class='lang-dot wp'></span>WordPress",
      "<span class='lang-dot el'></span>Elementor",
      "<span class='lang-dot wc'></span>WooCommerce",
    ],
  },
  {
    id: 10,
    title: "Mid_Town_Dental",
    category: "Dental",
    img: "https://res.cloudinary.com/getmonirh/image/upload/v1643609197/monirhossain/portfolio/midtowndentalgroup_xoiraj.jpg",
    subtitle: "Dental clinic wordpress website",
    key: "Mid Town Dental elementor wordpress woocommerce ",
    url: "https://midtowndentalgroup.com/",
    compatible: [
      "<span class='lang-dot wp'></span>WordPress",
      "<span class='lang-dot el'></span>Elementor",
      "<span class='lang-dot wc'></span>WooCommerce",
    ],
  },
  {
    id: 11,
    title: "Cbeaux",
    category: "Fashion Shop",
    img: "https://res.cloudinary.com/getmonirh/image/upload/v1643609197/monirhossain/portfolio/cbeaux_c23jzr.jpg",
    subtitle: "Fashion ecommerce website",
    key: "cbeaux fashion shop ecommerce website woocommerce",
    url: "https://cbeaux.com/",
    compatible: [
      "<span class='lang-dot wp'></span>WordPress",
      "<span class='lang-dot el'></span>Elementor",
      "<span class='lang-dot wc'></span>WooCommerce",
    ],
  },
  {
    id: 12,
    title: "Belleview_Dental",
    category: "Dental",
    img: "https://res.cloudinary.com/getmonirh/image/upload/v1643609197/monirhossain/portfolio/belleviewdental_ijlc1s.jpg",
    subtitle: "Dental clinic website with elementor pro",
    key: "Belleview Dental clinic website with elementor pro wordpress",
    url: "https://belleviewdental.com.au/",
    compatible: [
      "<span class='lang-dot wp'></span>WordPress",
      "<span class='lang-dot el'></span>Elementor",
      "<span class='lang-dot wc'></span>WooCommerce",
    ],
  },
  {
    id: 13,
    title: "Control_Post",
    category: "Portfolio",
    img: "https://res.cloudinary.com/getmonirh/image/upload/v1643609195/monirhossain/portfolio/control-post_dcbpgi.jpg",
    subtitle: "Creative video creator portfolio website",
    key: "portfolio video agency portfolio website wordpress woocommerce control post html bootstrap css",
    url: "https://controlpost.org/",
    compatible: [
      "<span class='lang-dot html'></span>HTML",
      "<span class='lang-dot css'></span>CSS",
      "<span class='lang-dot bt'></span>Bootstrap",
    ],
  },
  {
    id: 14,
    title: "British_Knights",
    category: "Fashion Shop",
    img: "https://res.cloudinary.com/getmonirh/image/upload/v1643609197/monirhossain/portfolio/britishknights_cseitb.jpg",
    subtitle: "Fashion shop with woocommerce wordpress woocommerce",
    key: "British Knights",
    url: "https://britishknights.com/",
    compatible: [
      "<span class='lang-dot wp'></span>WordPress",
      "<span class='lang-dot el'></span>Elementor",
      "<span class='lang-dot wc'></span>WooCommerce",
    ],
  },
  {
    id: 15,
    title: "I_Love_Kick_Boxing",
    category: "Health / Fitness",
    img: "https://res.cloudinary.com/getmonirh/image/upload/v1643609198/monirhossain/portfolio/ilovekickboxing_g7oqgj.jpg",
    subtitle: "Online fitness website with wordpress",
    key: "i love kick boxing fitness website with wordpress elementor gym",
    url: "https://ilovekickboxing.com/",
    compatible: [
      "<span class='lang-dot wp'></span>WordPress",
      "<span class='lang-dot el'></span>Elementor",
      "<span class='lang-dot wc'></span>WooCommerce",
    ],
  },
  {
    id: 16,
    title: "No1_Intertrading",
    category: "Agency",
    img: "https://res.cloudinary.com/getmonirh/image/upload/v1643609197/monirhossain/portfolio/no1-it_gqp7dw.jpg",
    subtitle: "Trading Business website",
    key: "Bootstrap HTML css php business no1 Intertrading ",
    url: "http://no1-it.com/",
    compatible: [
      "<span class='lang-dot html'></span>HTML",
      "<span class='lang-dot css'></span>CSS",
      "<span class='lang-dot bt'></span>Bootstrap",
    ],
  },
  {
    id: 17,
    title: `TU'S_Dental`,
    category: "Dental",
    img: "https://res.cloudinary.com/getmonirh/image/upload/v1643609197/monirhossain/portfolio/tusdental_e1dhgc.jpg",
    subtitle: "Dental clinic website design",
    key: "tu dental wordpress website elementor clinic",
    url: "http://tusdental.com/",
    compatible: [
      "<span class='lang-dot wp'></span>WordPress",
      "<span class='lang-dot el'></span>Elementor",
      "<span class='lang-dot wc'></span>WooCommerce",
    ],
  },
  {
    id: 18,
    title: "Earth_Bound",
    category: "Pet Shop",
    img: "https://res.cloudinary.com/getmonirh/image/upload/v1643609198/monirhossain/portfolio/earthbounduk_d6cczr.jpg",
    subtitle: "",
    key: "Pet food woocommerce elementor wordpress Earth Bound",
    url: "http://www.earthbounduk.co.uk/",
    compatible: [
      "<span class='lang-dot wp'></span>WordPress",
      "<span class='lang-dot el'></span>Elementor",
      "<span class='lang-dot wc'></span>WooCommerce",
    ],
  },
  {
    id: 19,
    title: "Smile_Spa",
    category: "Spa",
    img: "https://res.cloudinary.com/getmonirh/image/upload/v1643609197/monirhossain/portfolio/nycsmilespa_cg3sbf.jpg",
    subtitle: "Spa WordPress Elementor",
    key: "spa WordPress Elementor smile elementor",
    url: "http://www.nycsmilespa.com/",
    compatible: [
      "<span class='lang-dot wp'></span>WordPress",
      "<span class='lang-dot el'></span>Elementor",
      "<span class='lang-dot wc'></span>WooCommerce",
    ],
  },
  {
    id: 20,
    title: "Felt_Moon",
    category: "Pet Shop",
    img: "https://res.cloudinary.com/getmonirh/image/upload/v1643609197/monirhossain/portfolio/feltmoon_chv41q.jpg",
    subtitle: "Felted Personalised Pet Portraits",
    key: "Felt Moon pet shop wordpress woocommerce elementor",
    url: "https://www.felt-moon.co.uk/",
    compatible: [
      "<span class='lang-dot wp'></span>WordPress",
      "<span class='lang-dot el'></span>Elementor",
      "<span class='lang-dot wc'></span>WooCommerce",
    ],
  },
];
