import { Box } from "@mui/material";
import Head from "next/head";

export default function IndexPage() {
  return (
    <>
      <Head>
        <title>Monir portfolio || by next.js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box sx={{ display: "flex", flexWrap: "wrap", gap: "5px" }}>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus ipsa,
        mollitia laudantium reprehenderit aperiam, veniam illum delectus
        perferendis totam consectetur eum modi alias fugit explicabo tempora
        vitae rem, eaque esse? Quos ipsa a quae veniam culpa unde nihil
        consequatur voluptatem maiores cum, aspernatur voluptatum amet. Quaerat
        beatae incidunt quae labore illo a numquam debitis veniam vitae
        exercitationem eveniet, deleniti recusandae? Ipsa, sit doloremque! Fugit
        iure inventore, culpa iusto soluta magnam, tempora distinctio qui a
        amet, quam possimus totam? Tempore cumque optio est earum recusandae
        cupiditate ipsa at quae, impedit corporis? Possimus accusantium delectus
        amet repellendus repellat, aut quibusdam odit in aspernatur, vitae eaque
        corporis velit aperiam sequi atque magnam quisquam ipsum architecto
        rerum tempore accusamus. Libero praesentium culpa exercitationem odio
        rerum iste quos, unde fugiat atque sunt iure doloremque laudantium quod
        assumenda enim non corporis, possimus consectetur in. Reiciendis
        veritatis deleniti nobis perferendis saepe illo, eveniet debitis
        quisquam sapiente qui iste sed fugit labore deserunt aperiam eaque
        corporis optio non vitae aliquam a ab voluptate. Saepe reiciendis
        aperiam repellendus voluptatibus quod aut voluptatem, asperiores ex
        recusandae, debitis deleniti tempore sed magnam voluptates. Dicta soluta
        voluptas nostrum nobis eveniet vel esse excepturi et facere eaque
        assumenda quidem, dolores odio harum modi quaerat nemo laborum sunt
        tempora ipsam earum necessitatibus? Inventore quas officiis ex dolore
        fugiat asperiores commodi eos, ad earum doloribus at nesciunt id
        mollitia animi. Perferendis, unde voluptatibus aliquid quas excepturi
        nobis nihil suscipit, iste accusantium explicabo distinctio, iure
        quibusdam in dolorum eligendi ducimus aut quidem voluptate laboriosam
        sapiente fuga incidunt vitae cumque? Hic veritatis eveniet quasi eum
        beatae optio a sapiente esse. Voluptas, sit? Distinctio veniam at dolor
        ea autem delectus, provident facere. Est labore, quis suscipit
        voluptates, magni commodi, repudiandae fuga molestias quam sequi ut
        ducimus aliquam? Delectus consectetur est blanditiis voluptate tempore
        dolorem facere aliquam debitis nulla possimus magnam veritatis expedita
        doloremque ut, perferendis laborum soluta inventore cumque placeat animi
        assumenda nisi aspernatur accusantium. Ad, enim quibusdam esse
        laudantium quod, magni beatae fuga cupiditate, quae accusantium
        consequuntur unde. Earum, laborum hic. Deserunt molestiae et, libero
        mollitia tenetur at repellendus itaque asperiores eum harum debitis
        quidem assumenda est voluptatibus enim dolorum quia, cupiditate dolorem
        molestias quos! Repellendus, in omnis! Quidem, velit dolorem. Neque quam
        delectus commodi fugit et! Nostrum eius doloremque corrupti aliquam
        repellendus, laudantium odit numquam unde est perferendis at, nam animi
        suscipit adipisci debitis rerum magnam temporibus voluptatum velit iusto
        consectetur? Impedit, ab praesentium eveniet perferendis molestiae
        perspiciatis molestias sit ea maiores labore veniam itaque beatae
        necessitatibus veritatis repellat nobis. Ad nemo cumque alias at rerum
        placeat nisi expedita adipisci repellendus iusto odio delectus dolorem
        ducimus maiores incidunt eligendi voluptatibus, nam aut est sit
        exercitationem voluptatem dicta illum sunt! Quibusdam mollitia nisi ad
        officiis voluptatem, eum consequatur autem, aspernatur magni qui
        blanditiis officia sed, asperiores dolores. Blanditiis delectus
        inventore atque, nesciunt aperiam labore expedita sapiente nemo
        assumenda. Asperiores recusandae laborum accusamus natus nemo aliquam
        incidunt dicta consequuntur fugit ipsum, unde iste ut iure iusto
        consequatur repellat delectus aut aspernatur eligendi accusantium
        voluptate vero qui harum atque. Cupiditate, dolorem saepe voluptate nam
        totam explicabo dolores voluptatem quidem tempore ipsa veniam veritatis
        dicta obcaecati consequatur mollitia et! Ullam consequatur unde
        dignissimos numquam necessitatibus sint perspiciatis nisi, sit expedita.
        Veniam omnis dicta autem reprehenderit rerum corrupti quos magni
        sapiente libero cupiditate maxime neque, nemo temporibus, sequi dolore
        rem quis, inventore nulla itaque. Laboriosam, quisquam quos ducimus
        impedit sed repudiandae maxime sunt eum nemo veniam voluptatibus modi
        facere mollitia magnam ullam aut, tenetur beatae quod dicta rem cum!
        Eius odio, quae nisi explicabo dignissimos porro magnam distinctio
        maiores ad unde aut sunt reprehenderit numquam. Corporis debitis cumque
        officiis deserunt nihil aperiam sunt perferendis architecto esse
        cupiditate ullam eaque sint id ex velit provident, amet rerum ducimus
        blanditiis recusandae maxime quos mollitia delectus fuga. Deserunt
        minima architecto illo error esse repudiandae eius eligendi, qui ab
        fugiat sed, dicta numquam molestias delectus, ad optio voluptatum sint.
        Molestiae ad consequuntur voluptatem doloremque atque blanditiis
        assumenda corporis, cumque suscipit ipsum possimus modi pariatur labore
        vero error perferendis a officia odio iste deleniti ipsa. Fugit,
        mollitia omnis dolore doloribus magnam nulla quia cum numquam culpa
        error non voluptates? Nemo tempora quam temporibus dolore similique
        corrupti aperiam unde dicta! Illum non quidem provident ad? Quibusdam,
        maxime ipsum eligendi magni ducimus minima beatae sunt necessitatibus
        qui facilis deleniti sapiente, facere saepe, cupiditate id recusandae
        aliquid nihil ullam. Tempora rem amet possimus alias. Earum neque sit
        dignissimos quae sapiente a doloribus perferendis ipsam ea enim, iste
        perspiciatis vel at qui facilis, asperiores dolore tempore sint! Rem
        consequatur dicta debitis nemo fugiat maxime magni at atque quaerat
        dolores. Iste recusandae non vitae, hic eum quo ad labore iure. Placeat
        itaque voluptatum tempora voluptates earum a tempore fugiat eveniet qui
        eum eaque ad, soluta expedita porro rerum reiciendis dolore
        necessitatibus quas esse sapiente labore facilis nihil sint. Officiis
        accusantium repellat corporis amet, autem illo! Maxime accusantium
        quisquam, nemo, ad reprehenderit exercitationem officiis neque eaque
        iste animi sunt porro qui omnis expedita autem distinctio in veniam
        voluptas voluptatem praesentium. Incidunt praesentium ea architecto
        alias minima, ab iste voluptatum ratione nemo distinctio, quis quaerat
        totam eos cupiditate voluptatibus repudiandae. Veritatis earum quaerat
        nihil ipsa unde a sequi quos nesciunt quibusdam porro commodi nemo
        laborum quo, maxime delectus asperiores repudiandae omnis repellendus
        deserunt officia. Est cum quam consequatur, expedita nostrum nobis eos
        molestias dolor? Accusantium rem reprehenderit recusandae? Consequuntur
        enim, quae rem saepe fuga dignissimos quas nostrum magni eius odio, quod
        exercitationem. Sapiente cumque, deleniti pariatur illum accusamus hic
        perferendis alias accusantium! Ducimus quibusdam molestiae aliquid amet
        voluptatibus asperiores ratione eos dolor enim. Voluptatum, consequatur
        voluptas saepe eum alias ducimus, dignissimos placeat dolor iusto minima
        laborum quos distinctio debitis odit, pariatur qui repellat. Nobis,
        possimus similique laudantium laborum facilis dolor debitis fugit
        molestias ab! Distinctio id, dignissimos quis corporis exercitationem
        excepturi? Maxime beatae veritatis suscipit optio sunt aut atque error
        esse ipsam rerum facilis expedita nemo, obcaecati nostrum praesentium
        tenetur similique provident voluptates. Nihil reprehenderit tenetur a,
        in animi minus consectetur ratione voluptatem reiciendis, veniam
        voluptates quae assumenda natus, aperiam quod facilis sunt ex impedit
        odit iure architecto cum ea numquam sed. Natus quasi itaque animi atque
        alias. Dolorum, voluptas a quisquam dignissimos, vero doloremque
        consectetur eos optio qui aut rerum atque tempora incidunt quas suscipit
        officiis laborum nesciunt odit quo odio est excepturi esse. Suscipit
        consectetur fugiat mollitia voluptates, harum soluta iusto ut vitae.
        Facilis iusto similique perferendis! Saepe minus in neque assumenda
        corrupti facilis, quisquam sequi dolor. Pariatur inventore amet sunt
        fugiat doloremque, modi possimus eveniet velit. Quae quaerat molestias
        soluta in cupiditate eligendi veniam voluptatibus amet a alias quam
        suscipit esse dolores tempora, officia vel cumque omnis fugiat explicabo
        expedita fugit mollitia impedit! Aliquid vitae neque quidem unde,
        consequatur id architecto incidunt dolorum error. Minus, nesciunt
        voluptatum. Aut debitis fugit sint consequatur dolorem sequi quas
        corrupti magni perspiciatis voluptates repellat incidunt deserunt, dolor
        architecto sit praesentium reprehenderit facere nesciunt! Earum ad ex
        rerum? Reprehenderit, atque. Cupiditate voluptatum amet libero,
        voluptatibus sed est velit neque praesentium, iure sint reiciendis nisi
        repellendus quia. Obcaecati reiciendis voluptate eos eum laboriosam
        repudiandae doloribus quisquam molestiae, deserunt commodi quo pariatur
        voluptas omnis dolore, sequi sint delectus ipsam. In repellat maxime,
        fugit mollitia perferendis ipsa repudiandae autem eveniet ipsam saepe
        vitae expedita non iusto doloremque reprehenderit dicta quod laborum
        odio assumenda? Vero veniam quis atque cumque voluptas reiciendis
        quibusdam necessitatibus dicta officiis. Necessitatibus dicta
        consectetur, eligendi itaque quae magnam vel soluta praesentium a
        expedita perferendis nihil numquam quisquam omnis. Optio, quis iste?
        Veniam, porro id impedit iusto quisquam laboriosam, architecto aperiam
        voluptate sit dicta esse quaerat est, quo dolores doloribus provident
        vero! Omnis quo commodi ducimus sapiente earum accusantium sunt quod
        adipisci numquam magni, amet harum maiores iusto, consequatur dolor
        iste? Provident a unde eaque deleniti laboriosam ratione placeat
        tenetur. Excepturi explicabo ex fuga. Suscipit doloribus quisquam,
        exercitationem a enim natus inventore rem officiis dolor. Blanditiis est
        quam inventore nam fugiat eligendi similique enim repudiandae sunt
        veniam consequuntur atque accusantium quisquam sequi ad facilis
        voluptates veritatis nulla dignissimos, natus in nihil ratione.
        Voluptatum magnam pariatur et, sapiente quis architecto quod in sequi
        est tempora repellat, totam voluptates. Quas sint temporibus quasi
        voluptates officiis vero iusto repudiandae nulla qui excepturi unde
        cupiditate laboriosam explicabo, dignissimos quibusdam ratione suscipit
        sed iure provident. Autem provident voluptas mollitia ab modi omnis
        optio quas quo unde delectus nostrum sunt a voluptatem voluptatibus
        porro at quaerat culpa ipsa consectetur incidunt quibusdam dolores,
        laudantium minus quam. Nisi explicabo sed repellat amet tempore
        temporibus impedit. Illo facere perferendis commodi a delectus ad animi
        exercitationem incidunt molestiae, quia voluptas labore fugit nihil
        accusantium non! Sint, hic. Ad consectetur incidunt iste vero assumenda
        quae enim commodi quaerat perferendis? Ut consequuntur sapiente animi
        totam, earum natus! Et perferendis quo neque cupiditate, beatae
        voluptate itaque nesciunt nulla necessitatibus reiciendis dolore ipsam
        harum asperiores fugiat eveniet voluptates dicta? Temporibus, doloremque
        fugit quae ea rem quo officia, deserunt nulla, facilis laboriosam
        voluptatem! Suscipit rerum ut quibusdam eum quod est facilis quaerat
        expedita neque iure, fuga voluptates tempore tempora, perferendis a
        mollitia optio veniam corrupti ad excepturi aliquam sit? Neque aperiam
        qui voluptatum ullam ipsam porro vero nobis ipsum sunt aut ipsa aliquid
        pariatur quidem rem, fugit eius modi nam, impedit esse quibusdam quia!
        Totam placeat quaerat suscipit assumenda natus obcaecati doloremque nemo
        pariatur hic molestias. Maiores quos, explicabo facere illum quibusdam
        saepe aliquid obcaecati nemo necessitatibus dignissimos, voluptatum
        inventore cumque rerum soluta nulla beatae atque voluptatem possimus
        corporis blanditiis pariatur? Facere deleniti cupiditate, nam a
        explicabo provident ea suscipit reiciendis laborum odio. Praesentium
        iure accusantium reprehenderit hic doloremque maiores! Ad voluptatum
        totam consectetur commodi ut sed quia corrupti recusandae magni eius
        quas quisquam dignissimos, nesciunt veniam sunt, enim unde! Hic totam
        obcaecati magnam reiciendis ratione rem unde ea, laudantium cupiditate
        sunt quod repellat delectus incidunt deserunt sed repellendus accusamus.
        Voluptate vero excepturi officiis porro cum adipisci nam ab mollitia
        nobis possimus, recusandae suscipit asperiores saepe odio consequatur
        itaque obcaecati. Tempore molestiae porro et illo ad corrupti,
        necessitatibus ex deserunt repellat odit obcaecati quidem! Eum ea animi,
        alias, deleniti eveniet non at voluptatibus impedit iste velit ratione
        dignissimos magni quas. Eligendi, unde veritatis animi magni possimus
        cupiditate itaque quo, corporis expedita enim explicabo laudantium odio
        minus consequatur repellat fugit odit assumenda illo nostrum? Minima
        dolorum ea quis alias libero nulla facilis dolor sed? Fuga unde tempora
        praesentium est aperiam sint voluptas animi enim repellendus voluptate
        quos incidunt soluta, harum a et molestiae suscipit quidem fugit alias
        sequi dolorum? Nam, voluptatibus exercitationem molestias est nemo
        numquam illo voluptatem minus labore, at laudantium! Culpa corrupti,
        esse illo accusamus ab sint! At officiis nobis, qui totam quisquam error
        eveniet, illo corporis dolor quibusdam aperiam! Delectus dolor autem ab
        cum quas provident magni tempora magnam veritatis molestiae vero
        suscipit et, soluta rem ad. Ullam quidem adipisci eum voluptatibus
        maiores veniam repellendus ad atque? Quidem animi neque quisquam
        ducimus? Ipsam nostrum ea ad placeat? Unde nostrum cum ad saepe soluta
        doloremque labore praesentium similique eius dolores! Veniam quidem
        illum dolore molestias cumque commodi adipisci fugiat corporis deleniti
        fuga voluptatibus explicabo tenetur quo minus minima doloribus,
        praesentium omnis delectus facere quis perspiciatis ut? Saepe,
        voluptates. Id error porro inventore necessitatibus quibusdam harum
        repellendus obcaecati saepe natus laudantium enim possimus voluptatibus
        omnis consequatur officia totam consectetur pariatur, mollitia repellat
        ut. Repellat, eius. Molestiae id minus quidem eligendi voluptates culpa
        reprehenderit! Fugiat, corporis debitis eum ipsum, aut alias quis ipsam
        placeat reprehenderit ex accusamus molestiae aperiam animi enim aliquid
        modi ipsa possimus fuga voluptate ut perferendis voluptates? Est et
        dolorum consectetur iste aperiam! Odit ut enim aliquam quidem earum
        voluptatibus corporis? Error rerum, dolor expedita a perferendis neque,
        quis dolorum nam et dolores minima earum dicta ipsa ut necessitatibus.
        Reiciendis asperiores iusto fuga laborum. Autem praesentium ex labore,
        mollitia quae impedit nobis. Officia omnis voluptates adipisci pariatur
        error ab, mollitia animi aliquam voluptatibus at velit qui, quod quaerat
        vel necessitatibus. Veritatis quidem incidunt enim unde officia
        accusantium eos eaque neque nam magni ex iste necessitatibus
        exercitationem illum animi consectetur velit consequuntur recusandae
        facilis mollitia quia, tenetur est consequatur molestias. Recusandae
        accusamus at, porro enim numquam repudiandae accusantium necessitatibus
        temporibus.
      </Box>
    </>
  );
}

// server side rendering
export const getServerSideProps = async (ctx) => {
  const res = await fetch("http://localhost:3000/api/products");
  const pizzaData = await res.json();

  return {
    props: {
      pizzaData,
    },
  };
};
