import { Box, Typography, styled } from "@mui/material";
import Head from "next/head";
import { AboutHead, Container, HeadContent, Main } from "./about";
import { createFluidValue } from "@/common/hooks/FluidValue/mix/FluidValue";
import Search from "@/common/components/Search/Search";
import Filter from "@/common/components/Filter/Filter";
import Products from "@/common/components/Products/Products";
import Image from "next/image";
import Link from "next/link";

const HeroDes = styled("div")(({ theme }) =>
  theme.unstable_sx({
    "& p": {
      mb: "0",
      fontSize: createFluidValue(1, 1.1),
      fontWeight: "300",
      lineHeight: "1.4",
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      alignItems: "center",
      py: createFluidValue(1.5, 1.5),
      width: { xs: "100%", sm: "100%", md: "66%" },
      margin: "0 auto",
      textAlign: "center",
      textJustify: "inter-word",
    },
  })
);

const ProductDisplay = styled("div")(({ theme }) =>
  theme.unstable_sx({
    py: createFluidValue(2, 2),
    display: "grid",
    gridTemplateColumns: {
      xs: "repeat(1, 1fr)",
      sm: "repeat(2, 1fr)",
      md: "repeat(2, 1fr)",
    },
    gridTemplateRows: "1fr",
    gridColumnGap: "20px",
    gridRowGap: "10px",
    margin: "0 auto",
  })
);

const ProductCard = styled("div")(({ theme }) =>
  theme.unstable_sx({
    "& img": {
      height: "auto",
      width: "100%",
    },
    "&  a": {
      color: "inherit",
    },
  })
);

export default function IndexPage({ productsData }) {
  console.log(productsData);
  return (
    <>
      <Head>
        <title>Monir portfolio || by next.js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Container>
          <AboutHead>
            <HeadContent>
              <Box
                sx={{
                  display: "flex",
                  flexDirection: "column",
                  justifyContent: "center",
                  alignItems: "center",
                }}
              >
                <Typography component="p">{"Hi, I'm Monir"}</Typography>
                <Typography component="p" style={{ textAlign: "center" }}>
                  {"Welcome to my portfolio."}
                </Typography>
              </Box>
            </HeadContent>
            <HeroDes>
              <Typography component={"p"}>
                {
                  "I enjoy sharing the projects just as much as I enjoy creating them. Sit back & take a moment to browse through some of my completed work."
                }
              </Typography>
            </HeroDes>
          </AboutHead>
          {/* search section */}
          <Search />
          <Filter />
          <ProductDisplay>
            {productsData.map((product) => (
              <ProductCard key={product.id}>
                <Link href={`http://localhost:3000/${product.title}`} passHref>
                  <Image
                    src={product.img}
                    alt="product"
                    width={400}
                    height={500}
                    priority
                  />
                  <p>{product.title}</p>
                  <p>{product.category}</p>
                </Link>
              </ProductCard>
            ))}
          </ProductDisplay>
        </Container>
      </Main>
    </>
  );
}

// server side rendering
export const getServerSideProps = async (ctx) => {
  const res = await fetch("http://localhost:3000/api/products");
  const productsData = await res.json();
  return {
    props: {
      productsData,
    },
  };
};
